// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxacmzjiabagjljwfsvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4YWNtemppYWJhZ2psandmc3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0ODQzNjIsImV4cCI6MjA1MDA2MDM2Mn0.Ou_-TI3AOH9kc4Sc6fvvI5maw6WBogJGxV1RuAptl9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);